.TH "TDA" 3 "Viernes, 31 de Octubre de 2014" "Version 0.1.1" "Traductor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TDA \- 
.PP
instancia de este \fBTDA\fP es una palabra en el idioma origen, que lleva además asociada sus traducciones en el idioma al que se quiere traducir\&.  

.SH SYNOPSIS
.br
.PP
.SH "Descripción detallada"
.PP 
instancia de este \fBTDA\fP es una palabra en el idioma origen, que lleva además asociada sus traducciones en el idioma al que se quiere traducir\&. 

instancia de este \fBTDA\fP es un diccionario traductor que contiene todas las palabras de un idioma junto con sus traducciones en el idioma al que se quiere traducir\&. 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Traductor del código fuente\&.
